chore: refactor CI
* Handle version strings like '7', '70', '7.1.0', etc.
* Auto-convert '6.0' to LTS
* Allow specifying a patch version
* Automatically detect when running in CI, and treat warnings as errors
* Refactor justfile

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -1,4 +1,4 @@
-name: Build
+name: CI
 
 on:
   push:
@@ -9,84 +9,107 @@ on:
     types: [ published ]
   workflow_dispatch:
 
+defaults:
+  run:
+    shell: bash
+
 jobs:
   test:
+    name: Test Varnish latest
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
+        uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
+      - name: Ensure this crate has not yet been published (on release)
+        run: just check-all-if-published
+      - run: just install-varnish
+      - run: just -v ci-test
+      - name: Test for latest Varnish version
+        run: just ci-test-extras
+      - name: Check semver
+        uses: obi1kenobi/cargo-semver-checks-action@v2
+        with:
+          exclude: varnish-sys  # GitHub CI somehow generated a different output
+      - name: Test packaging for publish
+        run: |
+          rustup install nightly --profile minimal
+          just clean test-publish
+
+  test-older:
+    name: Test Varnish ${{ matrix.ver }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
       matrix:
         include:
-          # The default version is set in the justfile. If setup is blank, will use default.
-          # To update tests for all versions, run `just bless-all`
-          - type: latest
-          - setup: varnish76
-            version: "7.6.3-*"
-          - setup: varnish60lts
-            version: "6.0.14-*"
-    env:
-      RUST_BACKTRACE: 1
-      RUSTDOCFLAGS: -D warnings
-      RUSTFLAGS: -D warnings
+          # This list must match the justfile list for supported_varnish_vers var without the latest version
+          - ver: 7.6
+          - ver: 7.5
+          - ver: 6.0
     steps:
-      - uses: taiki-e/install-action@v2
-        with: { tool: just }
       - uses: actions/checkout@v4
-      - if: matrix.type == 'latest'
-        name: Ensure this crate has not yet been published (on release)
-        run: just check-all-if-published
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
-      - run: just install-varnish ${{ matrix.setup }} ${{ matrix.version }}
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
+      - run: just install-varnish ${{ matrix.ver }}
       - run: just -v ci-test
-      - if: matrix.type == 'latest'
-        name: Test for latest Varnish version
-        run: just ci-test-extras
-      - if: matrix.type == 'latest'
-        name: Check semver
-        uses: obi1kenobi/cargo-semver-checks-action@v2
-        with:
-          exclude: varnish-sys  # GitHub CI somehow generated a different output
-      - if: matrix.type == 'latest'
-        name: Test packaging for publish
-        run: |
-          rustup install nightly --profile minimal
-          just clean test-publish
-        #
-        # MSRV Test - should be done after all the regular tests with the latest Rust are done
-        #
-      - if: matrix.type == 'latest'
-        name: Read crate metadata
+
+  test-msrv:
+    name: Test MSRV
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
+        uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
+      - name: Read MSRV
         id: msrv
-        run: echo "value=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT
-      - if: matrix.type == 'latest'
-        name: Install Rust
+        run: echo "value=$(just get-msrv)" >> $GITHUB_OUTPUT
+      - name: Install MSRV Rust ${{ steps.msrv.outputs.value }}
         uses: dtolnay/rust-toolchain@stable
         with:
           toolchain: ${{ steps.msrv.outputs.value }}
           components: rustfmt
-      - if: matrix.type == 'latest'
-        run: just -v ci-test-msrv
+      - run: just install-varnish
+      - run: just ci_mode=0 ci-test-msrv  # Ignore warnings in MSRV
 
   # Ensure that the docs can be built at docs.rs without varnish dependencies
   test-docs-rs:
     runs-on: ubuntu-latest
     steps:
-      - uses: taiki-e/install-action@v2
-        with: { tool: just }
       - uses: actions/checkout@v4
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
       - name: Ensure docs can be built at docs.rs without varnish dependencies
         run: just ci-test-docs-rs
 
-  publish:
-    if: startsWith(github.ref, 'refs/tags/')
-    needs: [ test, test-docs-rs ]
+  # This job checks if any of the previous jobs failed or were canceled.
+  # This approach also allows some jobs to be skipped if they are not needed.
+  ci-passed:
+    if: always()
+    needs: [ test, test-older, test-msrv, test-docs-rs ]
     runs-on: ubuntu-latest
     steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
+
+  release:
+    # Some dependencies of the `ci-passed` job might be skipped, but we still want to run if the `ci-passed` job succeeded.
+    if: always() && startsWith(github.ref, 'refs/tags/') && needs.ci-passed.result == 'success'
+    name: Publish to crates.io
+    needs: [ ci-passed ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
       - uses: taiki-e/install-action@v2
         with: { tool: just }
-      - uses: actions/checkout@v4
       - run: just install-varnish
       - name: Publish to crates.io
         run: just publish
